# Generated by Django 4.1.9 on 2023-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditScoreAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='creditHistoryAge',
            field=models.CharField(max_length=10),
        ),
    ]
